"""Forensic Reporting Engine for DEEPTRACE-X.

Generates court-and-research-grade forensic audit dossiers:
- Standardized Markdown (.md) reports with cryptographic chain-of-custody,
  multi-signal evidence logs, and academic disclaimers.
- Structured JSON (.json) forensic certificates.
"""

from datetime import datetime, timezone
from typing import Dict, Any, Optional
from backend.database.models import Analysis


class ReportService:
    @staticmethod
    def generate_markdown_report(analysis: Analysis) -> str:
        """Constructs a comprehensive, standardized Markdown forensic audit report."""
        created_str = analysis.created_at.strftime("%Y-%m-%d %H:%M:%S UTC") if analysis.created_at else "N/A"
        report_timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

        # Models table
        model_rows = []
        for p in analysis.model_predictions:
            status_str = "Ready" if p.status == "READY" else f"Standby ({p.status})"
            conf_str = f"{p.confidence * 100:.1f}%" if p.status == "READY" else "N/A"
            model_rows.append(
                f"| {p.model_name} | {p.model_version} | {p.prediction} | {conf_str} | {p.processing_time_ms:.1f} ms | {status_str} |"
            )
        models_table = "\n".join(model_rows) if model_rows else "| None | - | - | - | - | - |"

        # Evidence table
        evidence_rows = []
        for e in analysis.evidence_items:
            evidence_rows.append(
                f"| `{e.evidence_type}` | {e.source_model} | {e.score:.4f} | {e.description} |"
            )
        evidence_table = "\n".join(evidence_rows) if evidence_rows else "| None | - | - | - |"

        # Robustness table
        robustness_rows = []
        if analysis.robustness_tests:
            for t in analysis.robustness_tests:
                delta_sign = "+" if t.score_delta > 0 else ""
                robustness_rows.append(
                    f"| {t.transformation.replace('_', ' ')} | `{t.parameter}` | {t.prediction} | {delta_sign}{t.score_delta:.3f} | {t.uncertainty_delta:+.3f} |"
                )
        robustness_table = "\n".join(robustness_rows) if robustness_rows else "| Not yet executed | - | - | - | - |"

        report = f"""# DEEPTRACE-X Forensic Analysis Dossier
**Academic & Research AI Image Authenticity Audit**
*Document Reference: DTX-{analysis.uuid.upper()}*

---

### Executive Summary

| Parameter | Assessment Value |
|---|---|
| **Primary Verdict** | **{analysis.overall_verdict}** |
| **Calibrated Score** | **{analysis.overall_score * 100:.1f}%** (0% = Authentic, 100% = Manipulated) |
| **Forensic Uncertainty** | **{analysis.uncertainty_score * 100:.1f}% ({analysis.uncertainty_label})** |
| **Input Quality Status** | **{analysis.image_quality_label or 'NORMAL'}** (Score: {((analysis.image_quality_score or 0.85) * 100):.0f}/100) |
| **Face Localization** | **{analysis.face_count} face(s) localized** |
| **Total Analysis Latency** | **{analysis.processing_time_ms:.1f} ms** |

---

### 1. Cryptographic Chain-of-Custody & Evidence Metadata

- **Subject Filename**: `{analysis.filename}`
- **SHA-256 Cryptographic Digest**: `{analysis.file_hash}`
- **Storage Artifact**: `{analysis.stored_path}`
- **MIME Media Type**: `{analysis.media_type}`
- **File Size**: `{analysis.file_size_bytes:,} bytes`
- **Spatial Dimensions**: `{analysis.width} x {analysis.height} pixels`
- **Ingestion Timestamp**: `{created_str}`
- **Report Generation Timestamp**: `{report_timestamp}`
- **Forensic Engine**: `DEEPTRACE-X v1.0 (Academic Build)`

---

### 2. Multi-Signal Neural Detector Hypotheses

| Detector Model | Version | Hypothesis | Confidence | Latency | Status |
|---|---|---|---|---|---|
{models_table}

---

### 3. Verifiable Forensic Evidence Ledger

| Forensic Indicator | Source Engine | Score | Technical Finding |
|---|---|---|---|
{evidence_table}

---

### 4. Robustness & Perturbation Testing Profile

| Perturbation Transform | Parameter | Post-Test Verdict | Score Drift (Δs) | Uncertainty Shift (ΔU) |
|---|---|---|---|---|
{robustness_table}

---

### 5. Scientific & Legal Disclaimers

> [!IMPORTANT]
> **Probabilistic Forensic Evaluation Disclaimer**:
> This report was automatically generated by the DEEPTRACE-X Adaptive Multi-Signal Forensics Platform.
> All verdicts, confidence scores, and uncertainty indices represent statistical technical probabilities derived
> from machine-learning models, frequency-domain transformations, and semantic foundation embeddings.
> 
> 1. This document does **not** constitute an incontrovertible certificate of absolute authenticity or manipulation.
> 2. Novel or unseen generative diffusion architectures may exhibit distribution shifts requiring manual expert verification.
> 3. Results should always be interpreted by a qualified human digital forensics investigator in conjunction with source provenance and contextual evidence.

---
*DEEPTRACE-X — Developed for College Research & Project Expo Presentation*
"""
        return report

    @staticmethod
    def generate_json_certificate(analysis: Analysis) -> Dict[str, Any]:
        """Constructs a machine-readable JSON forensic certificate."""
        created_str = analysis.created_at.isoformat() if analysis.created_at else None
        now_str = datetime.now(timezone.utc).isoformat()

        return {
            "schema_version": "1.0",
            "system": "DEEPTRACE-X",
            "dossier_uuid": analysis.uuid,
            "generated_at": now_str,
            "custody": {
                "filename": analysis.filename,
                "file_hash_sha256": analysis.file_hash,
                "media_type": analysis.media_type,
                "file_size_bytes": analysis.file_size_bytes,
                "dimensions": {"width": analysis.width, "height": analysis.height},
                "ingested_at": created_str,
            },
            "assessment": {
                "overall_verdict": analysis.overall_verdict,
                "calibrated_manipulation_score": round(float(analysis.overall_score), 4),
                "uncertainty_score": round(float(analysis.uncertainty_score), 4),
                "uncertainty_label": analysis.uncertainty_label,
                "image_quality_score": round(float(analysis.image_quality_score), 4) if analysis.image_quality_score else None,
                "image_quality_label": analysis.image_quality_label,
                "face_count": analysis.face_count,
                "processing_time_ms": analysis.processing_time_ms
            },
            "model_predictions": [
                {
                    "model_name": p.model_name,
                    "model_version": p.model_version,
                    "prediction": p.prediction,
                    "confidence": p.confidence,
                    "processing_time_ms": p.processing_time_ms,
                    "status": p.status
                } for p in analysis.model_predictions
            ],
            "evidence_items": [
                {
                    "evidence_type": e.evidence_type,
                    "score": e.score,
                    "source_model": e.source_model,
                    "description": e.description
                } for e in analysis.evidence_items
            ],
            "robustness_tests": [
                {
                    "transformation": t.transformation,
                    "parameter": t.parameter,
                    "prediction": t.prediction,
                    "score_delta": t.score_delta,
                    "uncertainty_delta": t.uncertainty_delta
                } for t in analysis.robustness_tests
            ] if analysis.robustness_tests else [],
            "disclaimer": (
                "Probabilistic technical evaluation only. Not proof of manipulation. "
                "Human forensic expert review required."
            )
        }
